
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

# TODO: fork the repo to checkin artifacts, or find an alternative repo that has artifacts available.
# This repo includes only istio-generated files.

### BEGIN Mixer codegen deps

required = [
  "github.com/googleapis/googleapis",
  "github.com/gogo/protobuf/proto",
  "github.com/gogo/protobuf/jsonpb",
  "github.com/gogo/protobuf/protoc-gen-gogoslick",
  "github.com/gogo/protobuf/gogoproto",
]

### END Mixer codegen deps

# TODO: remove Envoy API codegen deps section once
# https://github.com/golang/dep/issues/1306 is fixed. Currently 
# dep chokes if a constraint only contains non-go files.
 
### BEGIN Envoy API codegen deps
#
#   Revisions under metadata are valid dependencies and are used to
#   generate go files from protos, like those defined for Envoy's v2
#   APIs.
#
#   See bin/build-envoy-api.sh for details.
#
#   Modifying anything under metadata will also need a review of
#   bin/build-envoy-api.sh for updating protoc imports and plugin
#	mappings.
#   GOGO_PROTO_APIs  A space separated list of identifiers for
#                    each REPO, example: "SOME_API SOME_OTHER_API"
#   [API]_REPO       The repo to use, example, acme.io/apis
#   [API]_PROJECT    The project in that repo, example: protoclibs. The
#                    project must exist under acme.io/apis/protoclibs
#   [API]_PROTOS     A space separated list of folders containing
#                    protocol buffer definition files having file
#                    extension '.proto'. Use * for wildcards, and must
#                    start with "*/" and end with "*.proto", example: 
#                    "*/service/*.proto */ui/*.proto"
#   [API]_EXCLUSIONS A space separated list of directories to exclude
#                    for protobufs that may not be required but are
#                    problematic in terms of dependencies.
#   [API]_REVISION   The SHA of the repository's revision.
[metadata]
GOGO_PROTO_APIS	= "LYFT_PROTOC_GEN_VALIDATE ENVOYPROXY_DATA_PLANE_API"

LYFT_PROTOC_GEN_VALIDATE_REPO        = "github.com/lyft"
LYFT_PROTOC_GEN_VALIDATE_PROJECT     = "protoc-gen-validate"
LYFT_PROTOC_GEN_VALIDATE_PROTOS      = "*/validate/validate.proto"
LYFT_PROTOC_GEN_VALIDATE_EXCLUSIONS  = ""
LYFT_PROTOC_GEN_VALIDATE_REVISION    = "8e6aaf55f4954f1ef9d3ee2e8f5a50e79cc04f8f"

ENVOYPROXY_DATA_PLANE_API_REPO       = "github.com/envoyproxy"
ENVOYPROXY_DATA_PLANE_API_PROJECT    = "data-plane-api"
ENVOYPROXY_DATA_PLANE_API_PROTOS     = "*/api/*.proto"
ENVOYPROXY_DATA_PLANE_API_EXCLUSIONS = "*/metrics_service.proto"
ENVOYPROXY_DATA_PLANE_API_REVISION   = "7d740da8fc19dac2132403b7456bdca477a1b70a"

### END Envoy API codegen deps

[[constraint]]
  name = "github.com/googleapis/googleapis"
  source = "https://github.com/costinm/googleapis.git"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "^1.8.2" # match istio/api


# When necessary, override transitive contraints that might be pinned
# to older versions (e.g. ingress-nginx pinned to 1.8).

[[override]]
  name = "k8s.io/client-go"
  branch = "release-6.0"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "release-1.9"

[[override]]
  name = "k8s.io/api"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "release-1.9"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.9"

# Keep k8s.io/ingress-nginx pinned to an older version until istio
# ingress code is refactored.
#
# istio.io/istio/pilot/adapter/config/ingress uses the following nginx
# controller packages from an older version of k8s.io/ingress which
# have since been made internal and are no longer available.
#
#     "k8s.io/ingress-nginx/core/pkg/ingress/status"
#     "k8s.io/ingress-nginx/core/pkg/ingress/store"
#     "k8s.io/ingress-nginx/core/pkg/ingress/annotations/class"
[[constraint]]
  name = "k8s.io/ingress-nginx"
  revision = "0c6f15e372c831de52fcc393932540bb3a6d51b5"

[[constraint]]
  name = "github.com/russross/blackfriday"
  revision = "4048872b16cc0fc2c5fd9eacf0ed2c2fedaa0c8c"

[[constraint]]
  name = "code.cloudfoundry.org/copilot"
  revision = "03646eb993243c330f30e3053523da4e8c0850ab"

[[override]]
  name = "github.com/ugorji/go"
  revision = "708a42d246822952f38190a8d8c4e6b16a0e600c"

[[override]]
 name = "github.com/apache/thrift"
 version = ">=0.9.3, <0.11.0"

### DO NOT PIN these repos to master. It will result in inconsistent builds in circleci
### as we cache dep ensure.
[[constraint]]
  name = "istio.io/api"
  revision = "934c38563b4fc7827ac5f9120c085d3b9a56c1ad"

[[constraint]]
  name = "istio.io/fortio"
  revision = "6684bc54abfa793ee4beffe8b2a5b9ec83c782e3"


### Begin Mixer codegen dep pinning

[[override]]
  name = "github.com/gogo/protobuf"
  version = "=0.5"

### End Mixer codegen dep pinning

[[constraint]]
  name = "github.com/open-policy-agent/opa"
  version = "0.5.13"
